### ISSUE TITLE
Missing blockaddress.pl in sendmail_parse

### ISSUE THREAD

**Issue by Stujordan** [blankcode/msipdelta#10]
Hi,

I've cloned your project but it references blockaddress.pl which isn't included:

./msipdelta.sh: line 33: /scripts/microsoft/msipdelta/blockaddress.pl: No such file or directory

sendmail_parse () {
  #Start parsing IPs for sendmail
  cat "$OUTPUT_DIR/$IMPORT" | while read list
    do
      echo "$list" | "$INSTALL_DIR/blockaddress.pl" >> "$FOR_IMPORT/$IMPORT"; ##Write the expanded output to a file.
    done
}

**Comment by blankcode** [comment]
Greetings Stujordan, 

That PERL script is not mine. I can see if I can get permission to share it via the repository. 

Thank you 
Brian Blankenship

**Comment by blankcode** [comment]
Greetings Stujordan,

Good news turns out that script is vastly open source so I can provide it for the project. I'll do that as soon as I have time to.

Thank you
Brian Blankenship

**Comment by blankcode** [comment]
There are some lines in there that call out to github to update the repo to, you will want to comment those out. You're the first person to clone it so I've not needed to tackle this yet.

**Comment by Stujordan** [comment]
Yeah, commented those out already, in fact quite a bit of it I didn't need :D

TBH it's the parse/splitting into separate files in the List folder that's the useful bit, saves me reinventing the wheel. I can then compare the diff to my firewall config and send out a suggested firewall update to be committed manually.

Thanks for sharing it.
________________________________

**Comment by Stujordan** [comment]
Oh, I should also say you've left in your absolute paths /home/brianblahblah/ in the code etc..


________________________________

**Comment by blankcode** [comment]
Greetings Stujordan,

I have now included the blockaddress.pl and fixed the file path. There are some paths that need to be absolute and do reference my user's home. That's due to this is meant to be run by cron and it logs on as it's own user. I'm going to make one that is meant to be run by a user at will. But this is what we have today.

Thank you,
Brian Blankenship

**Comment by blankcode** [comment]
Greetings Stujordan,

Ok, I t took less time that I thought to take out the code related to automating the git updates. I made a new copy sans git support called no_cron_msipdelta.sh, that you can run as a one off. you can point the log directory vars where you need them.

Thank you,
Brian Blankenship
